services:
  web:
    image: bryangerlach/episodes:latest
    restart: unless-stopped
    environment:
      SECRET_KEY: "%qufh2ea8!-$%_ctzw=in*d2__i#s*3_mph82!+(3m9g*!%@tt"
      CSRF_TRUSTED_ORIGINS: "http://localhost"
    ports:
      - "3000:3000"
    volumes: 
      - db-data:/app/db
    dns:
      - 8.8.8.8

volumes:
  db-data: