# Generated by Django 5.0.3 on 2024-11-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0009_auto_20160823_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='watch_later',
            field=models.BooleanField(default=False),
        ),
    ]
