# Generated by Django 5.0.3 on 2024-11-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0010_show_watch_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='stopped_watching',
            field=models.BooleanField(default=False),
        ),
    ]
