# Generated by Django 5.0.3 on 2024-11-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0011_show_stopped_watching'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='imbdID',
            new_name='imdbID',
        ),
    ]
