# Generated by Django 5.0.3 on 2024-11-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0012_rename_imbdid_show_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='language',
            field=models.CharField(default='eng', max_length=10),
        ),
    ]
