# Generated by Django 5.0.3 on 2024-11-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0014_episode_episodeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='date_watched',
            field=models.DateField(blank=True, null=True),
        ),
    ]
