# Generated by Django 5.0.3 on 2024-11-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0017_show_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='finaleType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
