# Generated by Django 5.0.3 on 2024-12-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0018_episode_finaletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='airsDays',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='airsTime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='delayWatch',
            field=models.IntegerField(default=0),
        ),
    ]
