# Generated by Django 5.0.3 on 2024-12-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0019_show_airsdays_show_airstime_show_delaywatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='airsDays',
            field=models.JSONField(default=dict),
        ),
    ]
