# Generated by Django 5.0.3 on 2025-01-22 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0020_alter_show_airsdays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tvdbID', models.CharField(max_length=50)),
                ('extended_title', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=150, null=True)),
                ('overview', models.TextField()),
                ('imdbID', models.CharField(blank=True, max_length=50, null=True)),
                ('status_watched', models.BooleanField(default=False)),
                ('date_watched', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('studio', models.CharField(max_length=50)),
                ('genre_list', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
