# Generated by Django 5.0.3 on 2025-01-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0021_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='extended_title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
