# Generated by Django 5.0.3 on 2025-08-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0022_rename_extended_title_movie_name_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='imdbID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
