# Generated by Django 5.0.3 on 2026-09-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0023_episode_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='runtime',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
