# Generated by Django 5.0.3 on 2026-09-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0024_episode_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='runningStatus',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='status_watched',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='stopped_watching',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='watch_later',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
